service: aws-lamdda-crud-node
disabledDeprecations:
  - CODE_1 # To disable specific deprecation with code "CODE_1"
  - '*'
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:sa-east-1:993020179356:table/taskTable

functions:
  api:
    handler: src/main.handler
    events:
      - httpApi:
          path: /
          method: get
  createTaks:
    handler: src/addTask.addTask
    events:
      - httpApi:
          path: /tasks
          method: post
  getTaks:
    handler: src/getTasks.getTasks
    events:
      - httpApi:
          path: /getTasks
          method: get
  getTaskById:
    handler: src/getTaskById.getTaskById
    events:
      - httpApi:
          path: /getTask/{id}
          method: get
  deleteTask:
    handler: src/deleteTask.deleteTask
    events:
      - httpApi:
          path: /delete-task/{id}
          method: delete
  updateTask:
    handler: src/updateTask.updateTask
    events:
      - httpApi:
          path: /task/{id}
          method: put

	
resources: # CloudFormation template syntax
  Resources:
    TaksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: taskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
